In [1]:
import matplotlib.pyplot as plt
from random import randint
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
%run 'Data_Munging.ipynb'

<class 'pandas.tslib.Timedelta'>
61.0


## 1) k-nearest neighbors classifier

On crée d'abord le testing set: 

In [103]:
d = 25
daySensor = [sensorData['Start time'][x].day == d and sensorData['End time'][x].day == d for x in range(1,len(sensorData))]
daySensor = daySensor + [False]
daySensorData = sensorData[daySensor]
daySensorData.index = np.arange(1,len(daySensorData)+1)

dayActivity = [activityData['Start time'][x].day == d and activityData['End time'][x].day == d for x in range(1,len(activityData))]
dayActivity = dayActivity + [False]
dayActivityData = activityData[dayActivity]
dayActivityData.index = np.arange(1,len(dayActivityData)+1)

testingFeatureMatrix, testingLabel = convert2LastFiredFeatureMatrix(daySensorData,dayActivityData,60)

cumuSen, cumuAct = cumulationTable(testingFeatureMatrix, testingLabel)

sensorTestingData = np.asarray(cumuSen)
labelTestingData = np.asarray(cumuAct)

In [111]:
2600 / 52

50

In [104]:
from sklearn.neighbors import KNeighborsClassifier

In [105]:
sensorTrainingData = np.asarray(cumuSensor)
labelTrainingData = np.asarray(cumuActivity)

In [106]:
knn = KNeighborsClassifier()#(n_neighbors=3, weights='distance')
knn.fit(sensorTrainingData, labelTrainingData)

predictLabel = knn.predict(sensorTestingData)

In [107]:
error_rate = 0.0
for i in xrange(len(predictLabel)):
    if predictLabel[i] != labelTestingData[i]: 
        error_rate += 1
print error_rate/len(predictLabel)

0.25


In [108]:
l = list(set(predictLabel))
l3 = list(reversed(l2))

In [109]:
confusion_matrix(predictLabel, labelTestingData, labels = l2)

array([[7, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [3, 0, 5, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [2, 0, 0, 0, 0, 1]])

In [110]:
def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(l))
    plt.xticks(tick_marks,l, rotation=45)
    plt.yticks(tick_marks, l)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')


# Compute confusion matrix
cm = confusion_matrix(labelTestingData, predictLabel)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.figure()
plot_confusion_matrix(cm)

# Normalize the confusion matrix by row (i.e by the number of samples in each class)
cm_normalized = cm.astype('float') / cm.sum(axis=0)#[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)
plt.figure()
plot_confusion_matrix(cm_normalized, title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[7 0 3 0 0 2 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2]]
Normalized confusion matrix
[[ 0.88  0.    0.38  0.    0.    0.67   nan  0.  ]
 [ 0.    1.    0.    0.    0.    0.     nan  0.  ]
 [ 0.    0.    0.62  0.    0.    0.     nan  0.  ]
 [ 0.    0.    0.    1.    0.    0.     nan  0.  ]
 [ 0.    0.    0.    0.    1.    0.     nan  0.  ]
 [ 0.    0.    0.    0.    0.    0.33   nan  0.  ]
 [ 0.12  0.    0.    0.    0.    0.     nan  0.  ]
 [ 0.    0.    0.    0.    0.    0.     nan  1.  ]]


In [102]:
1+1

2